#
# SPDX-FileCopyrightText: 2026 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Build open-zaak

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: false
        # renovate: datasource=docker depName=openzaak/open-zaak
        default: '1.28.2'

env:
  BUILD_VERSION: ${{ inputs.version }}

permissions:
  packages: write

jobs:
  build-arm64:
    name: Build arm64 image
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out open-zaak ${{ env.BUILD_VERSION }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: open-zaak/open-zaak
          ref: ${{ env.BUILD_VERSION }}

      - name: Build open-zaak ${{ env.BUILD_VERSION }} for arm64
        run: |
          docker build --tag ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.BUILD_VERSION }}-arm64 .
          docker push ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.BUILD_VERSION }}-arm64

  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out open-zaak ${{ env.BUILD_VERSION }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: open-zaak/open-zaak
          ref: ${{ env.BUILD_VERSION }}

      - name: Build open-zaak ${{ env.BUILD_VERSION }} for amd64
        run: |
          docker build --tag ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.BUILD_VERSION }}-amd64 .
          docker push ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.BUILD_VERSION }}-amd64

  merge-manifest:
    name: Merge manifest list
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.BUILD_VERSION }} \
            ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.BUILD_VERSION }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.BUILD_VERSION }}-arm64
          docker manifest push ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.BUILD_VERSION }}
