#
# SPDX-FileCopyrightText: 2026 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Build open-zaak

on:
  workflow_dispatch:
env:
  OPEN_ZAAK_VERSION: 1.26.0

permissions:
  packages: write

jobs:
  build-arm64:
    name: Build arm64 image
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out open-zaak ${{ env.OPEN_ZAAK_VERSION }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: open-zaak/open-zaak
          ref: ${{ env.OPEN_ZAAK_VERSION }}

      - name: Build open-zaak ${{ env.OPEN_ZAAK_VERSION }} for arm64
        run: |
          docker build --tag ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }}-arm64 .
          docker push ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }}-arm64

  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out open-zaak ${{ env.OPEN_ZAAK_VERSION }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: open-zaak/open-zaak
          ref: ${{ env.OPEN_ZAAK_VERSION }}

      - name: Build open-zaak ${{ env.OPEN_ZAAK_VERSION }} for amd64
        run: |
          docker build --tag ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }}-amd64 .
          docker push ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }}-amd64

  merge-manifest:
    name: Merge manifest list
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }} \
            ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }}-arm64
          docker manifest push ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }}
