#
# SPDX-FileCopyrightText: 2026 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Build test

on:
  workflow_dispatch:
    inputs:
      postgis_version:
        description: 'PostGIS version to build'
        required: false
        default: {{ POSTGIS_VERSION }}

env:
  POSTGIS_VERSION: 17-3.5
  BUILD_VERSION: ${{ inputs.postgis_version || POSTGIS_VERSION }}

permissions:
  packages: write

jobs:
  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out postgis ${{ env.BUILD_VERSION }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: postgis/docker-postgis

      - name: Build postgis ${{ env.BUILD_VERSION }} for amd64
        run: |
          (cd ${{ env.BUILD_VERSION }}; docker build --tag ghcr.io/${{ github.repository_owner }}/postgis:${{ env.BUILD_VERSION }}-amd64 .)
