#
# SPDX-FileCopyrightText: 2026 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Build objects-api

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: false
        # renovate: datasource=docker depName=maykinmedia/objects-api
        default: '3.6.0'

env:
  BUILD_VERSION: ${{ inputs.version }}

permissions:
  packages: write

jobs:
  build-arm64:
    name: Build arm64 image
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out objects-api ${{ env.BUILD_VERSION }}
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: maykinmedia/objects-api
          ref: ${{ env.BUILD_VERSION }}

      - name: Build objects-api ${{ env.BUILD_VERSION }} for arm64
        run: |
          docker build --tag ghcr.io/${{ github.repository_owner }}/objects-api:${{ env.BUILD_VERSION }}-arm64 .
          docker push ghcr.io/${{ github.repository_owner }}/objects-api:${{ env.BUILD_VERSION }}-arm64

  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out objects-api ${{ env.BUILD_VERSION }}
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: maykinmedia/objects-api
          ref: ${{ env.BUILD_VERSION }}

      - name: Build objects-api ${{ env.BUILD_VERSION }} for amd64
        run: |
          docker build --tag ghcr.io/${{ github.repository_owner }}/objects-api:${{ env.BUILD_VERSION }}-amd64 .
          docker push ghcr.io/${{ github.repository_owner }}/objects-api:${{ env.BUILD_VERSION }}-amd64

  merge-manifest:
    name: Merge manifest list
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/objects-api:${{ env.BUILD_VERSION }} \
            ghcr.io/${{ github.repository_owner }}/objects-api:${{ env.BUILD_VERSION }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/objects-api:${{ env.BUILD_VERSION }}-arm64
          docker manifest push ghcr.io/${{ github.repository_owner }}/objects-api:${{ env.BUILD_VERSION }}
